
#ifndef _EMULATOR_H      // UNIX way of preventing multiple inclusions.
#define _EMULATOR_H


/*
NAME
    
    Emulator - run the Quack 3200 machine code generated by the Assembler.

DESCRIPTION
    Emulator class - supports the emulation of Quack3200 programs


*/


class Emulator {

public:

    const static int MEMSZ = 100000;	// The size of the memory of the Quack3200.
    Emulator() {

        memset( m_memory, 0, MEMSZ * sizeof(int) );
    }
    // Records instructions and data into Quack3200 memory.
    bool insertMemory( int a_location, int a_contents );
    
    // Runs the Quack3200 program recorded in memory.
    bool runProgram( );

private:
    int m_location;  //memory location of a code to run
    int m_currentvalue; // machine code stored on memory
    int m_Opcodeval; // Opcode part of code
    int m_registerNumber; // Register value from code
    int m_Operandvalue; //Operand value from code
    int m_memory[MEMSZ];       // The memory of the Quack3200.
    int m_reg[10];	// The accumulator for the Quack3200
    int m_counter=0; // used as counter to store startlocation only once
};

#endif

